### ISSUE TITLE
VX-native Umbrella

### ISSUE THREAD

**Issue by browniefed** [hshoff/vx#246]
Working on https://github.com/browniefed/vx this will be an umbrella for issue for all the places that need a fixing. Will keep adding/checking off as progress happens.

- [ ] className? Doesn't seem like react-native-svg cares so that's nice, but maybe a transform to remove them
- [ ] withBoundingRects needs to not use React-DOM, externalize to vx-primitives.
- [ ] vx-brush: getCoordsFromEvent uses DOM node, need to figure out native implementation that would work.
- [ ] vx-drag: I don't think this is going to be performant on native, going to need to rework this to use Animated and a PanResponder or react-native-gesture-handler. Unsure
- [ ] vx-event: Non-dom version
- [ ] vx-legend: Depends on DOM, needs native version. Possibly combine vx-primitives to include DOM and Native too?
- [ ] vx-responsive: Needs native port
- [ ] vx-text: Text measurement relies on DOM
- [ ] vx-tooltip: Depends on DOM
- [ ] vx-pattern: Pattern. react-native-svg doesn't support a Pattern element yet.
- [x] ~~vx-gradient: Gradient default props are 0%/100%, expected native values are 0 to 1, inject a prop parser for gradient~~ JK, 0% and 100% work.
- [ ] vx-gradient: gradientTransform needs it's own transformer

**Comment by techniq** [comment]
Awesome work thus far @browniefed 

It would be great if we also considered how supporting `<canvas />` might work (not related to react-native, but might influence the overall implementation).  I would image using something like [react-konva](https://github.com/lavrton/react-konva) to provide the primitives.  This is primarily tracked in #41 but thought it was worth mentioning here.

**Comment by browniefed** [comment]
Partly been following an implementation for a quick injection system that that Leland Richardson uses for `Animated`. My only hesitation with going with generic primitives is need a transformation layer for some of the minor differences between DOM svg/react-native-svg.

However, with a slightly custom primitive system built for each system to do necessary transforms in render targeting the under-lying interface. Quickly looking at konva it looks like support for gradients is weird but there shouldn't be too many issues with another primitive setting.

**Comment by browniefed** [comment]
I'm sure there will need to be more refactoring, I see Konva doesn't have a TSpan as well.

**Comment by techniq** [comment]
@browniefed I'm also not sure how much benefit will be gained with using something like `Konva`/`react-konva` to provide canvas support, since it will ultimately be adding a component to each canvas entity, which basically returns us back to svg (at least at a high level)

Should probably do some preliminary performance / benefit gains to adding canvas support in general before we venture to far down, but thought it was worth bringing up in this context.

**Comment by browniefed** [comment]
I have some demoes working now in the app, https://github.com/browniefed/vx
You'll need to use haul since it actually follows symlinks.
The getting started is pretty straight forward https://github.com/callstack/haul#getting-started

Some work is needed on touch based stuff, so I'm going to attempt that, I doubt it's going to be easy.

The main issue how I've set stuff up, and the need for additional primitives (View/Text/etc) to be used for tooltips and stuff. So going to need to also figure that whole thing out.

**Comment by lahwran** [comment]
what's the status of this project? any hope of getting something like the WIP of this into the automated tests of the main vx project, so that if progress is made on react-native porting, it sticks?

**Comment by browniefed** [comment]
I don't use graphs anymore on RN so I'd need to do some work.
